/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MandatoryDisclosureRouteImport } from './routes/mandatory-disclosure'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MandatoryDisclosureRoute = MandatoryDisclosureRouteImport.update({
  id: '/mandatory-disclosure',
  path: '/mandatory-disclosure',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/mandatory-disclosure': typeof MandatoryDisclosureRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/mandatory-disclosure'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/mandatory-disclosure'
  id: '__root__' | '/' | '/mandatory-disclosure'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MandatoryDisclosureRoute: typeof MandatoryDisclosureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mandatory-disclosure': {
      id: '/mandatory-disclosure'
      path: '/mandatory-disclosure'
      fullPath: '/mandatory-disclosure'
      preLoaderRoute: typeof MandatoryDisclosureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MandatoryDisclosureRoute: MandatoryDisclosureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
